name: Main

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build arm64
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w" -o vallox-mqtt-arm64 .
      - name: Build arm
        env:
          GOOS: linux
          GOARCH: arm
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w" -o vallox-mqtt-arm .
      - name: Build amd64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w" -o vallox-mqtt-amd64 .
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vallox-mqtt-arm64
            vallox-mqtt-arm
            vallox-mqtt-amd64
          draft: true
          generate_release_notes: true
